# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"

Rails.application.load_tasks

namespace :events do
  task :subscribe => :environment do
    $redis.subscribe("eventually") do |on|
      on.message do |channel, message|
        puts("Broadcast on channel #{channel}")
        UtilSubscriber.call(message)
      end
    end
  end
end
