alpha:        bundle exec rake run["alpha"]
alpha_sub:    bundle exec rake sub["alpha"]
beta:         bundle exec rake run["beta"]
beta_sub:     bundle exec rake sub["beta"]
charlie:      bundle exec rake run["charlie"]
charlie_sub:  bundle exec rake sub["charlie"]
overlord:     bundle exec rake run["overlord"]
overlord_sub: bundle exec rake sub["overlord"]
